on:
  push:
    branches: [main]
  pull_request:
name: Flatpak_release
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      name: "Build"
      with:
        bundle: write-shm.flatpak
        manifest-path: network.koesling.write-shm.yml
        cache-key: flatpak-builder-${{ github.sha }}